DROP DATABASE IF EXISTS BIBLIO;
CREATE DATABASE BIBLIO;
USE BIBLIO;
CREATE TABLE SOCIO(numero INT AUTO_INCREMENT, nombre VARCHAR(20) NOT NULL, direccion VARCHAR(30), numeroTelefono VARCHAR(15), fecha DATE,  PRIMARY KEY(numero));
CREATE TABLE LIBRO(numero INT AUTO_INCREMENT, titulo VARCHAR(30), autor VARCHAR(20), fechaEditado DATE, PRIMARY KEY(numero), UNIQUE(titulo));
