DROP DATABASE IF EXISTS HELLO; 
CREATE DATABASE HELLO;
USE HELLO;
CREATE TABLE PADRE(ID INT, PRIMARY KEY(ID));
CREATE TABLE HIJO(ID INT, ID_PADRE INT, FOREIGN KEY(ID_PADRE) REFERENCES PADRE(ID) ON UPDATE SET NULL);
INSERT INTO PADRE VALUES(1);
INSERT INTO HIJO VALUES(1,1);
UPDATE PADRE SET ID=2 WHERE ID=1;

