DROP DATABASE IF EXISTS BBDD;
CREATE DATABASE BBDD;
USE BBDD
CREATE TABLE tab1(
			col1 INTEGER,
			col2 CHAR(25) NOT NULL,
			col3 INTEGER,
			col4 INTEGER,
			PRIMARY KEY(col1),
			UNIQUE(col2),
			CONSTRAINT FK_TAB FOREIGN KEY(col3) REFERENCES tab1(col1),
			CONSTRAINT FK_TAB1 FOREIGN KEY(col4) REFERENCES tab1(col1)
			);
