DROP DATABASE IF EXISTS GRAMMAR;
CREATE DATABASE GRAMMAR;
USE GRAMMAR
CREATE TABLE tab1(col1 INTEGER , col2 CHAR(25) , col3 INTEGER, col4 CHAR(25),PRIMARY KEY(col1,col2), CONSTRAINT fk1 FOREIGN KEY(col3) REFERENCES tab1(col1));
