CREATE TABLE TABLA(nombre VARCHAR(20), BBDD VARCHAR(20), PRIMARY KEY(nombre,BBDD));
CREATE TABLE CAMPO(nombre VARCHAR(20) PRIMARY KEY, tipo VARCHAR(20),TABLA_nombre VARCHAR(20), FOREIGN KEY(TABLA_nombre) REFERENCES TABLA(nombre) ON DELETE CASCADE);

