DROP DATABASE IF EXISTS CALDERONSL;
CREATE DATABASE CALDERONSL;
USE CALDERONSL;
CREATE TABLE CLIENTES (DNI CHAR(9), nombre VARCHAR(20), apellidos VARCHAR(30), telefono INT(9), email VARCHAR(30), PRIMARY KEY(DNI), UNIQUE(telefono, email));
CREATE TABLE MOVILES (nombre VARCHAR(20), provincia VARCHAR(20),localidad VARCHAR(20), direccion VARCHAR(20), telefono INT(9), diaApertura DATE, diaCierre DATE, horaApertura TIME(4), horaCierre TIME(4), PRIMARY KEY(nombre), UNIQUE(telefono)); 
CREATE TABLE OPERADORAS
