/*
1. USAR IF EXISTS IF NOT EXISTS
2. TODAS LAS PK DEBEN DE AUTOINCREMENTARSE
3. AÑO DE TIPO YEAR
4. TODOS LOS CAMPOS DEBEN DECLARARSE COMO FK
5. CHARSET SOPORTE LA Ñ Y ACENTOS
6. TABLAS CUANDO SE ACTUALICEN LAS FK SE MODIFIQUE AUTOMATICAMENTE EN TODAS
7. TABLAS CUANDO SE BORREN LAS FK SE MODIFIQUE A NULO
8. ELIMINAR CODIGOSUPERIOR_PERSONAJES
9. AÑADIR LADO FUERZA EN LA TABLA PERSONAJES Y QUE SOLO COJAN JEDI O SITH
10. CARGAR OTRO ARCHIVO SOLO CON LOS DATOS A RELLENAR.
11. ACTUALIZAR UN DATO DE UNA TABLA NO CLAVE
12. ACTUALIZAR ALGUN VALOR DE LA TABLA CLAVE PRINCIPAL
13. ACTUALIZAR ALGUN VALOR DE LA TABLA CLAVE FORÁNEA
14. BORRAR UN DATO DE LA TABLA NO CLAVE
15. BORRAR UN DATO DE LA TABLA CLAVE PRINCIPAL
16. BORRAR DATO CLAVE FK DE ALGUNA TABLA
17. BORRAR TABLA VISITA
18. BORRAR TABLA ACTOR*/
DROP DATABASE IF EXISTS star;
CREATE DATABASE star;
USE star 
CREATE TABLE ACTOR(
			codigo INT, 
			nombre VARCHAR(40), 
			fecha DATE, 
			nacionalidad VARCHAR(20), 
			PRIMARY KEY(codigo)
			);
CREATE TABLE PERSONAJE(
			codigo INT, 
			nombre VARCHAR(40), 
			raza VARCHAR(40),
			grado INT,
			codigo_ACTOR INT, 
			codigoSuperior_PERSONAJE INT, 
			PRIMARY KEY(codigo,codigo_ACTOR, codigoSuperior_PERSONAJE), 
			FOREIGN KEY(codigo_ACTOR) REFERENCES ACTOR(codigo),
			FOREIGN KEY(codigoSuperior_PERSONAJE) REFERENCES PERSONAJE(codigo)
				);
CREATE TABLE PLANETA (
			codigo INT, 
			galaxia VARCHAR(20), 
			nombre VARCHAR(20), 
			PRIMARY KEY(codigo)
				);
CREATE TABLE PELICULA (
				codigo INT, 
				titulo VARCHAR(20), 
				director VARCHAR(40), 
				año INT, 
				PRIMARY KEY(codigo)
				);
CREATE TABLE NAVE(
				codigo INT, 
				nºtripulantes INT , 
				nombre VARCHAR(20), 
				PRIMARY KEY(codigo)
				);
CREATE TABLE PERSONAJEPELICULA (
				codigo_PERSONAJE INT, 
				codigo_PELICULA INT,
				PRIMARY KEY(codigo_PERSONAJE,codigo_PELICULA), 
				FOREIGN KEY(codigo_PERSONAJE) REFERENCES PERSONAJE(codigo), 
				FOREIGN KEY(codigo_PELICULA) REFERENCES PELICULA(codigo)
				);
CREATE TABLE VISITA(
				codigo_NAVE INT, 
				codigo_PLANETA INT, 
				codigo_PELICULA INT, 
				PRIMARY KEY(codigo_NAVE, codigo_PLANETA, codigo_PELICULA), 
				FOREIGN KEY(codigo_NAVE) REFERENCES NAVE(codigo), 
				FOREIGN KEY(codigo_PLANETA) REFERENCES PLANETA(codigo), 
				FOREIGN KEY(codigo_PELICULA) REFERENCES PELICULA(codigo)
				);
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE ACTOR MODIFY  codigo INT AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE PERSONAJE MODIFY codigo INT AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE PLANETA MODIFY codigo INT AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE PELICULA MODIFY codigo INT AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS = 1;
SET FOREIGN_KEY_CHECKS = 0;
ALTER TABLE NAVE MODIFY codigo INT AUTO_INCREMENT;
SET FOREIGN_KEY_CHECKS = 1;
ALTER TABLE PELICULA MODIFY año YEAR;
ALTER TABLE PERSONAJE DROP FOREIGN KEY PERSONAJE_ibfk_1;
ALTER TABLE PERSONAJE DROP FOREIGN KEY PERSONAJE_ibfk_2;
ALTER TABLE PERSONAJE ADD CONSTRAINT FOREIGN KEY (codigo_ACTOR) REFERENCES ACTOR(codigo) ON UPDATE CASCADE ON DELETE SET NULL;
ALTER TABLE PERSONAJE ADD CONSTRAINT FOREIGN KEY (codigoSuperior_PERSONAJE) REFERENCES PERSONA(codigo) ;






