SHOW DATABASES;
DROP DATABASE IF EXISTS METEO;
CREATE DATABASE METEO;
USE METEO
CREATE TABLE CIUDAD(codigo INT, nombre VARCHAR(30), PRIMARY KEY(codigo));
CREATE TABLE TEMPERATURA(dia DATE, codigo_CIUDAD INT, grados FLOAT, CONSTRAINT FK_CIUDAD1 FOREIGN KEY(codigo_CIUDAD) REFERENCES CIUDAD(codigo));
CREATE TABLE HUMEDAD(dia DATE, codigo_CIUDAD INT, PORCENTAJE FLOAT, CONSTRAINT FK_CIUDAD2 FOREIGN KEY(codigo_CIUDAD) REFERENCES CIUDAD(codigo));
CREATE TABLE INFORME(ID INT AUTO_INCREMENT, dia DATE, codigo_CIUDAD INT, PRIMARY KEY(ID), CONSTRAINT FK_CIUDAD3 FOREIGN KEY(codigo_CIUDAD) REFERENCES CIUDAD(codigo));
INSERT INTO CIUDAD VALUES (100,'Madrid'),(101,'Merida');
INSERT INTO TEMPERATURA VALUES('2018-01-12', 100, 13.4),('2018-01-12', 101, 5.9);
INSERT INTO HUMEDAD VALUES('2018-01-12',100,23.67),('2018-01-12',101,34.54);
INSERT INTO INFORME (dia,codigo_CIUDAD) VALUES('2018-01-12',100),('2018-01-12',101);
SELECT * FROM CIUDAD;
SELECT * FROM TEMPERATURA;
SELECT * FROM HUMEDAD;
SELECT * FROM INFORME;
