DROP DATABASE IF EXISTS ZOO;
CREATE DATABASE ZOO;
USE ZOO
CREATE TABLE ZOO(Nombre VARCHAR(20), Ciudad VARCHAR(20), Pais VARCHAR(20), Tamaño ENUM('CATEGORIA A','CATEGORIA B'), Presuspuesto FLOAT, PRIMARY KEY(Nombre));
CREATE TABLE ESPECIE(Nomcientifico VARCHAR(30) UNIQUE, Nomvulgar VARCHAR(30), Familia VARCHAR(30), Peligro VARCHAR(30), PRIMARY KEY(Nomcientifico));
CREATE TABLE ANIMAL(ID INT UNIQUE, nomzoo VARCHAR(20), nomespecie VARCHAR(20), Sexo ENUM('M','F'), Añonacim YEAR, PRIMARY KEY(ID), FOREIGN KEY(nomzoo) REFERENCES ZOO(Nombre), FOREIGN KEY(nomespecie) REFERENCES ESPECIE(Nomcientifico));

